CREATE PROCEDURE displayTypeofService ()
BEGIN
		SELECT REPORT.SUPP_ID, REPORT.SUPP_NAME, REPORT.AVERAGE,
        CASE
			WHEN ROPERT.AVARAGE > 5 THEN 'EXCELLENT SERVICE'
            WHEN REPORT.AVERAGE > 4 THEN 'GOOD SERVICE'
            WHEN REPORT.AVERAGE > 4 THEN 'AVERAGE SERVICE'
            ELSE 'POOR SERVICE'
END AS TYPE_OF_SERVICE FROM 
(
	SELECT FINAL.SUPP_ID, supplier.SUPP_NAME, FINAL.AVERAGE FROM
    (
		SELECT TEST2.SUPP_ID, SUM(TEST.RAT_RATSTARS)/COUNT(TEST2.RAT_RATSTARS) AS AVERAGE FROM
        (
			SELECT supplier_pricing.SUPP_ID, TEST.ORD_ID, TEST.RAT_RATSTARS FROM supplier_pricing
            INNER JOIN
            (
				SELECT `ORDER`.PRICING_ID, RATING.ORD_ID, RATING.RAT_RATSTARS FROM `ORDER`
			) AS TEST ON TEST.PRICING_ID = supplier_pricing.PRICING_ID
        ) AS TEST2 GROUP BY supplier_pricing.SUPP_ID
    ) AS FINAL
    INNER JOIN
    supplier WHERE FINAL.SUPP_ID = supplier.SUPP_ID
) AS REPORT;

END
