SELECT * from `order`;
select * from customer;

# JOIN THE BOTH TABLES
(SELECT `order`.*, CUSTOMER.CUS_NAME, CUSTOMER.CUS_GENDER FROM `order` INNER JOIN customer WHERE 
	`order`.CUS_ID HAVING `order`.ORD_AMOUNT >= 3000);
    
# DISPLAY RELEVNT COLUMN ONLY

SELECT T1.CUS_ID, T1.CUS_NAME, T1.CUS_GENDER, T1.ORD_AMOUNT FROM 
(
	SELECT `order`.*, customer.CUS_NAME, customer.CUS_GENDER FROM `order`
    INNER JOIN CUSTOMER WHERE `order`.CUS_ID=CUSTOMER.CUS_ID HAVING `order`.ORD_AMOUNT >= 3000
) AS T1 GROUP BY T1.CUS_ID;

# DISPLAY THE TOTAL NUMBER OF CUSTOMER BASED ON GENDER

SELECT * FROM
(
	SELECT T1.CUS_ID,T1.CUS_NAME,T1.CUS_GENDER,T1.ORD_AMOUNT FROM 
    (
		SELECT `order`.*, customer.CUS_NAME, customer.CUS_GENDER FROM `order`
        INNER JOIN customer WHERE `order`.CUS_ID = CUSTOMER.CUS_ID HAVING `order`.ORD_AMOUNT>=3000
	) AS T1 GROUP BY T1.CUS_ID
) AS T2 GROUP BY T2.CUS_GENDER;

#==========================================

SELECT COUNT(T2.CUS_GENDER) AS NO_OF_CUSTOMERS, T2.CUS_GENDER FROM 
(
	SELECT T1.CUS_ID, T1.CUS_NAME, T1.CUS_GENDER, T1.ORD_AMOUNT FROM
    (
		SELECT `order`.*, customer.CUS_NAME, customer.CUS_GENDER FROM `order`
        INNER JOIN customer WHERE `order`.CUS_ID =customer.CUS_ID HAVING `order`.ORD_AMOUNT>=3000
	) AS T1 GROUP BY T1.CUS_ID
) AS T2 GROUP BY T2.CUS_GENDER;