SELECT CUS_NAME, PRO_NAME, ORD_ID, ORD_DATE
FROM product AS P, supplier_pricing AS SP,
`order` AS ORD, customer AS CUS
WHERE
CUS.CUS_ID = 2 AND 
CUS.CUS_ID = ORD.CUS_ID AND
P.PRO_ID = SP.PRO_ID AND
ORD.PRICING_ID = SP.PRICING_ID
