SELECT PROD.PRO_ID, PROD.PRO_NAME FROM `order` AS ORD
INNER JOIN supplier_pricing AS SP
ON SP.PRICING_ID = ORD.PRICING_ID
INNER JOIN product AS PROD 
ON PROD.PRO_ID = SP.PRO_ID WHERE ORD.ORD_DATE > '2021-10-05';